ALTER TABLE expediente2
MODIFY COLUMN diagnostico VARBINARY(1000) NOT NULL,  
MODIFY COLUMN tratamiento VARBINARY(1000) NOT NULL,
ADD COLUMN diag_tag VARCHAR(16) NOT NULL,
ADD COLUMN treat_tag VARCHAR(16) NOT NULL;
